### ISSUE TITLE
Add Laravel integration

### ISSUE THREAD

**Issue by danielboendergaard** [danielboendergaard/quickpay-api#1]
Service Provider
Facade
Config

**Comment by Reached** [comment]
Hey Daniel, are you planning to develop this further into a Laravel package? :)

**Comment by danielboendergaard** [comment]
Hey, sorry for the late answer. Since I created this issue, the codebase has changed a lot and I found a   more generic way of setting the Quickpay credentials globally. The way you use it right now is like this.

``` php
Kameli\Quickpay\Configuration::setDefaultQuickpayId($id)
Kameli\Quickpay\Configuration::setDefaultMd5Check($md5check)
```
